#!/usr/bin/env python3
"""Generate tool/names_zh.json from exercises-dataset English names."""
from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "exercises-dataset" / "data" / "exercises.json"
OUT = ROOT / "tool" / "names_zh.json"

# Longer phrases first — applied as substring replacements on lowercased text.
_RAW = [
    ("resistance band", "阻力带"),
    ("stability ball", "稳定球"),
    ("medicine ball", "药球"),
    ("bosu ball", "BOSU球"),
    ("exercise ball", "健身球"),
    ("swiss ball", "瑞士球"),
    ("smith machine", "史密斯机"),
    ("leverage machine", "杠杆器械"),
    ("sled machine", "雪橇机"),
    ("cable machine", "绳索机"),
    ("ez barbell", "弯杆杠铃"),
    ("ez-barbell", "弯杆杠铃"),
    ("ez bar", "弯杆"),
    ("ez-bar", "弯杆"),
    ("olympic barbell", "奥杆"),
    ("trap bar", "六角杠"),
    ("hex bar", "六角杠"),
    ("body weight", "自重"),
    ("bodyweight", "自重"),
    ("pull-ups", "引体向上"),
    ("pull-up", "引体向上"),
    ("pull ups", "引体向上"),
    ("pull up", "引体向上"),
    ("pullups", "引体向上"),
    ("pullup", "引体向上"),
    ("chin-ups", "反手引体向上"),
    ("chin-up", "反手引体向上"),
    ("chin up", "反手引体向上"),
    ("push-ups", "俯卧撑"),
    ("push-up", "俯卧撑"),
    ("push ups", "俯卧撑"),
    ("push up", "俯卧撑"),
    ("pushups", "俯卧撑"),
    ("pushup", "俯卧撑"),
    ("sit-ups", "仰卧起坐"),
    ("sit-up", "仰卧起坐"),
    ("sit ups", "仰卧起坐"),
    ("sit up", "仰卧起坐"),
    ("pull-downs", "下拉"),
    ("pull-down", "下拉"),
    ("pull downs", "下拉"),
    ("pull down", "下拉"),
    ("pulldowns", "下拉"),
    ("pulldown", "下拉"),
    ("lat pulldown", "高位下拉"),
    ("lat pull-down", "高位下拉"),
    ("bench press", "卧推"),
    ("chest press", "推胸"),
    ("shoulder press", "推肩"),
    ("military press", "军事推举"),
    ("overhead press", "过头推举"),
    ("arnold press", "阿诺德推举"),
    ("romanian deadlift", "罗马尼亚硬拉"),
    ("sumo deadlift", "相扑硬拉"),
    ("stiff leg deadlift", "直腿硬拉"),
    ("stiff-leg deadlift", "直腿硬拉"),
    ("deadlift", "硬拉"),
    ("hip thrust", "臀推"),
    ("leg press", "腿举"),
    ("leg curl", "腿弯举"),
    ("leg extension", "腿屈伸"),
    ("calf raises", "提踵"),
    ("calf raise", "提踵"),
    ("lateral raise", "侧平举"),
    ("front raise", "前平举"),
    ("rear delt fly", "后束飞鸟"),
    ("rear delt", "后束三角肌"),
    ("face pull", "面拉"),
    ("bent-over", "俯身"),
    ("bent over", "俯身"),
    ("upright row", "直立划船"),
    ("seated row", "坐姿划船"),
    ("barbell row", "杠铃划船"),
    ("dumbbell row", "哑铃划船"),
    ("t-bar row", "T杠划船"),
    ("t bar row", "T杠划船"),
    ("cable row", "绳索划船"),
    ("inverted row", "反向划船"),
    ("close-grip", "窄距"),
    ("close grip", "窄距"),
    ("wide-grip", "宽距"),
    ("wide grip", "宽距"),
    ("hammer curl", "锤式弯举"),
    ("preacher curl", "牧师凳弯举"),
    ("concentration curl", "集中弯举"),
    ("spider curl", "蜘蛛弯举"),
    ("incline curl", "上斜弯举"),
    ("skull crusher", "碎颅者"),
    ("skullcrusher", "碎颅者"),
    ("triceps extension", "肱三头伸展"),
    ("tricep extension", "肱三头伸展"),
    ("triceps pushdown", "肱三头下压"),
    ("tricep pushdown", "肱三头下压"),
    ("kickback", "后踢"),
    ("good morning", "早安式"),
    ("hip abduction", "髋外展"),
    ("hip adduction", "髋内收"),
    ("glute bridge", "臀桥"),
    ("glute kickback", "臀后踢"),
    ("mountain climber", "登山者"),
    ("jumping jacks", "开合跳"),
    ("jumping jack", "开合跳"),
    ("high knees", "高抬腿"),
    ("burpee", "波比跳"),
    ("box jump", "跳箱"),
    ("step-up", "登阶"),
    ("step up", "登阶"),
    ("split squat", "分腿蹲"),
    ("goblet squat", "高脚杯深蹲"),
    ("front squat", "前蹲"),
    ("back squat", "后蹲"),
    ("hack squat", "哈克深蹲"),
    ("wall sit", "靠墙静蹲"),
    ("pistol squat", "手枪深蹲"),
    ("sissy squat", "西西深蹲"),
    ("side plank", "侧平板"),
    ("plank", "平板支撑"),
    ("russian twist", "俄罗斯转体"),
    ("bicycle crunch", "自行车卷腹"),
    ("reverse crunch", "反向卷腹"),
    ("hanging leg raise", "悬垂举腿"),
    ("hanging knee raise", "悬垂提膝"),
    ("leg raise", "举腿"),
    ("knee raise", "提膝"),
    ("hyperextension", "山羊挺身"),
    ("back extension", "背部伸展"),
    ("farmer's walk", "农夫行走"),
    ("farmers walk", "农夫行走"),
    ("farmer walk", "农夫行走"),
    ("wrist curl", "腕弯举"),
    ("cable crossover", "绳索夹胸"),
    ("cable fly", "绳索飞鸟"),
    ("pec deck", "蝴蝶机"),
    ("chest flye", "夹胸飞鸟"),
    ("chest fly", "夹胸飞鸟"),
    ("muscle-up", "双力臂"),
    ("muscle up", "双力臂"),
    ("clean and jerk", "挺举"),
    ("clean and press", "高翻推举"),
    ("power clean", "高翻"),
    ("hang clean", "悬垂高翻"),
    ("kettlebell swing", "壶铃摆荡"),
    ("turkish get-up", "土耳其起立"),
    ("turkish get up", "土耳其起立"),
    ("battle ropes", "战绳"),
    ("battle rope", "战绳"),
    ("tire flip", "翻轮胎"),
    ("sled push", "推雪橇"),
    ("sled pull", "拉雪橇"),
    ("jump rope", "跳绳"),
    ("stationary bike", "固定单车"),
    ("air bike", "风阻单车"),
    ("assault bike", "风阻单车"),
    ("cross-body", "交叉"),
    ("cross body", "交叉"),
    ("one-arm", "单臂"),
    ("one arm", "单臂"),
    ("single-arm", "单臂"),
    ("single arm", "单臂"),
    ("single-leg", "单腿"),
    ("single leg", "单腿"),
    ("one-leg", "单腿"),
    ("one leg", "单腿"),
    ("two-arm", "双臂"),
    ("two arm", "双臂"),
    ("behind the neck", "颈后"),
    ("behind neck", "颈后"),
    ("all fours", "四肢着地"),
    ("on knees", "跪姿"),
    ("on floor", "地面"),
    ("straight legs", "直腿"),
    ("bent knees", "屈膝"),
    ("bent knee", "屈膝"),
    ("straight arm", "直臂"),
    ("bent arm", "屈臂"),
    ("palms up", "掌心向上"),
    ("palms down", "掌心向下"),
    ("side bends", "体侧屈"),
    ("side bend", "体侧屈"),
    ("toe touches", "摸脚尖"),
    ("toe touch", "摸脚尖"),
    ("heel touchers", "摸脚跟"),
    ("heel touch", "摸脚跟"),
    ("neck flexion", "颈屈"),
    ("neck extension", "颈伸"),
    ("neck rotation", "颈旋转"),
    ("shoulder shrug", "耸肩"),
    ("shrug", "耸肩"),
    ("shrugs", "耸肩"),
    ("upright", "直立"),
    ("decline", "下斜"),
    ("incline", "上斜"),
    ("seated", "坐姿"),
    ("standing", "站姿"),
    ("lying", "卧姿"),
    ("prone", "俯卧"),
    ("supine", "仰卧"),
    ("kneeling", "跪姿"),
    ("hanging", "悬垂"),
    ("overhead", "过头"),
    ("underhand", "反手"),
    ("overhand", "正手"),
    ("alternating", "交替"),
    ("alternate", "交替"),
    ("assisted", "辅助"),
    ("weighted", "负重"),
    ("isometric", "等长"),
    ("circular", "环绕"),
    ("circles", "环绕"),
    ("circle", "环绕"),
    ("rotation", "旋转"),
    ("rotations", "旋转"),
    ("twists", "转体"),
    ("twist", "转体"),
    ("stretching", "拉伸"),
    ("stretch", "拉伸"),
    ("lunges", "弓步"),
    ("lunge", "弓步"),
    ("crunches", "卷腹"),
    ("crunch", "卷腹"),
    ("dips", "双杠臂屈伸"),
    ("dip", "臂屈伸"),
    ("rows", "划船"),
    ("row", "划船"),
    ("presses", "推举"),
    ("press", "推举"),
    ("curls", "弯举"),
    ("curl", "弯举"),
    ("flyes", "飞鸟"),
    ("flies", "飞鸟"),
    ("flye", "飞鸟"),
    ("fly", "飞鸟"),
    ("raises", "抬举"),
    ("raise", "抬举"),
    ("squats", "深蹲"),
    ("squat", "深蹲"),
    ("extensions", "伸展"),
    ("extension", "伸展"),
    ("flexion", "屈曲"),
    ("abduction", "外展"),
    ("adduction", "内收"),
    ("jumps", "跳"),
    ("jump", "跳"),
    ("walk", "走"),
    ("run", "跑"),
    ("swings", "摆荡"),
    ("swing", "摆荡"),
    ("barbell", "杠铃"),
    ("dumbbell", "哑铃"),
    ("kettlebell", "壶铃"),
    ("cable", "绳索"),
    ("band", "弹力带"),
    ("machine", "器械"),
    ("smith", "史密斯"),
    ("bench", "凳"),
    ("floor", "地面"),
    ("ball", "球"),
    ("rope", "绳"),
    ("bar", "杆"),
    ("handles", "把手"),
    ("handle", "把手"),
    ("plates", "杠铃片"),
    ("plate", "杠铃片"),
    ("roller", "滚筒"),
    ("wheel", "轮"),
    ("v-bar", "V杠"),
    ("straight-bar", "直杆"),
    ("straight bar", "直杆"),
    ("landmine", "地雷杠"),
    ("suspension", "悬挂"),
    ("biceps", "肱二头肌"),
    ("triceps", "肱三头肌"),
    ("delts", "三角肌"),
    ("deltoid", "三角肌"),
    ("pecs", "胸肌"),
    ("pectoral", "胸肌"),
    ("lats", "背阔肌"),
    ("traps", "斜方肌"),
    ("abs", "腹肌"),
    ("glutes", "臀肌"),
    ("glute", "臀"),
    ("quads", "股四头肌"),
    ("quad", "股四头肌"),
    ("hamstrings", "腘绳肌"),
    ("hamstring", "腘绳肌"),
    ("calves", "小腿"),
    ("calf", "小腿"),
    ("forearms", "前臂"),
    ("forearm", "前臂"),
    ("shoulders", "肩"),
    ("shoulder", "肩"),
    ("chest", "胸"),
    ("back", "背"),
    ("waist", "腰"),
    ("core", "核心"),
    ("legs", "腿"),
    ("leg", "腿"),
    ("arms", "臂"),
    ("arm", "臂"),
    ("hips", "髋"),
    ("hip", "髋"),
    ("knees", "膝"),
    ("knee", "膝"),
    ("ankles", "踝"),
    ("ankle", "踝"),
    ("wrists", "腕"),
    ("wrist", "腕"),
    ("neck", "颈"),
    ("spine", "脊柱"),
    ("obliques", "腹斜肌"),
    ("oblique", "腹斜肌"),
    ("hands", "手"),
    ("hand", "手"),
    ("feet", "脚"),
    ("foot", "脚"),
    ("heels", "脚跟"),
    ("heel", "脚跟"),
    ("toes", "脚尖"),
    ("toe", "脚尖"),
    ("left", "左"),
    ("right", "右"),
    ("upper", "上"),
    ("lower", "下"),
    ("inner", "内"),
    ("outer", "外"),
    ("front", "前"),
    ("rear", "后"),
    ("side", "侧"),
    ("lateral", "侧"),
    ("high", "高"),
    ("low", "低"),
    ("wide", "宽"),
    ("narrow", "窄"),
    ("full", "完整"),
    ("half", "半"),
    ("partial", "部分"),
    ("straight", "直"),
    ("bent", "屈"),
    ("flexed", "屈曲"),
    ("parallel", "平行"),
    ("vertical", "垂直"),
    ("horizontal", "水平"),
    ("neutral", "对握"),
    ("pronated", "正握"),
    ("supinated", "反握"),
    ("grip", "握"),
    ("thumbs", "拇指"),
    ("thumb", "拇指"),
    ("palm", "掌"),
    ("palms", "掌"),
    ("snatch", "抓举"),
    ("clean", "翻站"),
    ("jerk", "挺"),
    ("thruster", "推举深蹲"),
    ("thrusters", "推举深蹲"),
    ("handstand", "倒立"),
    ("inverted", "反向"),
    ("reverse", "反向"),
    ("dynamic", "动态"),
    ("static", "静态"),
    ("explosive", "爆发"),
    ("slow", "慢速"),
    ("paused", "暂停"),
    ("deficit", "赤字"),
    ("sumo", "相扑"),
    ("conventional", "传统"),
    ("bulgarian", "保加利亚"),
    ("cossack", "哥萨克"),
    ("zercher", "泽彻"),
    ("jefferson", "杰弗逊"),
    ("superman", "超人"),
    ("spider", "蜘蛛"),
    ("dragon", "龙式"),
    ("archer", "弓箭手"),
    ("captain", "船长"),
    ("chair", "椅"),
    ("box", "箱"),
    ("step", "台阶"),
    ("steps", "台阶"),
    ("wall", "墙"),
    ("doorway", "门框"),
    ("table", "桌"),
    ("yoga", "瑜伽"),
    ("pose", "式"),
    ("cardio", "有氧"),
    ("aerobic", "有氧"),
    ("warmup", "热身"),
    ("warm-up", "热身"),
    ("cool-down", "放松"),
    ("cooldown", "放松"),
    ("activation", "激活"),
    ("mobility", "灵活度"),
    ("version", ""),
    ("variation", "变式"),
    ("style", "式"),
    ("with", "带"),
    ("and", "与"),
    ("using", "使用"),
    ("into", "至"),
    ("from", "从"),
    ("onto", "至"),
    ("over", "过"),
    ("under", "下"),
    ("across", "交叉"),
    ("apart", "分开"),
    ("together", "并拢"),
    ("both", "双"),
    ("double", "双"),
    ("single", "单"),
    ("two", "双"),
    ("one", "单"),
    ("three", "三"),
    ("quarter", "四分"),
    ("degrees", "度"),
    ("degree", "度"),
    ("male", ""),
    ("female", ""),
    ("on", ""),
    ("of", ""),
    ("the", ""),
    ("a", ""),
    ("an", ""),
    ("to", "至"),
    ("for", ""),
    ("in", ""),
    ("by", ""),
    ("or", "或"),
]

PHRASES = sorted(_RAW, key=lambda x: len(x[0]), reverse=True)


def translate_name(name: str) -> str:
    original = name.strip()
    s = re.sub(r"\s*\((male|female)\)\s*$", "", original, flags=re.I)
    s = s.replace("°", "度")

    fracs: list[str] = []

    def prot(m: re.Match[str]) -> str:
        fracs.append(m.group(0))
        return f"§F{len(fracs) - 1}§"

    work = re.sub(r"\d+/\d+", prot, s.lower())

    for en, zh in PHRASES:
        if en in work:
            work = work.replace(en, zh)

    # strip residual pure-english short noise tokens that are empty mappings leftovers
    work = re.sub(r"[()_,/]", " ", work)
    work = re.sub(r"\s+", " ", work).strip()

    for i, f in enumerate(fracs):
        work = work.replace(f"§F{i}§", f)

    cjk = len(re.findall(r"[\u4e00-\u9fff]", work))
    latin = len(re.findall(r"[A-Za-z]", work))
    if cjk > 0 and cjk >= latin:
        work = re.sub(r"\s+", "", work)
    else:
        work = re.sub(r"\s+", " ", work).strip()

    # If still mostly English, keep a readable bilingual-ish form: original English
    # but prefer our partial Chinese if any CJK present.
    if not work:
        return original
    if latin > cjk * 2 and cjk < 2:
        # fallback: keep original English title-cased lightly for searchability
        return original
    return work


def main() -> None:
    exercises = json.loads(SRC.read_text(encoding="utf-8"))
    names = {ex["id"]: translate_name(ex["name"]) for ex in exercises}
    assert len(names) == len(exercises)
    assert all(v.strip() for v in names.values())
    OUT.write_text(json.dumps(names, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    cjk = sum(1 for v in names.values() if re.search(r"[\u4e00-\u9fff]", v))
    pure = sum(1 for v in names.values() if not re.search(r"[A-Za-z]", v))
    print(f"wrote {OUT} total={len(names)} has_cjk={cjk} pure_zh={pure}")
    for ex in exercises[:12]:
        print(f"  {ex['id']}: {ex['name']!r} -> {names[ex['id']]!r}")


if __name__ == "__main__":
    main()
